apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: xwjwjuuvi-go 
  janus-idp.io/tekton: xwjwjuuvi-go
  backstage.io/kubernetes-id: xwjwjuuvi-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xwjwjuuvi-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml